# =================
# Style Cops
# =================
Style/ClassAndModuleChildren:
  EnforcedStyle: nested

Style/SymbolArray:
  EnforcedStyle: brackets
  MinSize: 1

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/FormatString:
  EnforcedStyle: sprintf

Style/NumericLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

# =================
# Metrics Cops
# =================
Metrics/MethodLength:
  Max: 15 # TODO: Work to bring this down
  CountAsOne: ['array', 'hash', 'heredoc']

Metrics/BlockLength:
  Exclude:
    - "spec/**/*_spec.rb"

# =================
# Layout Cops
# =================
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_space

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: aligned

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'lib/thrift/*'
    - 'lib/thrift/**/*'
    - 'node_modules/**/*'
    <% `git status --ignored --porcelain`.lines.grep(/^!! /).each do |path| %>
    - <%= path.sub(/^!! /, '') %>
    <% end %>
